#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
LIGHT_BLUE='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

if [ "$#" -lt 1 ]; then
    echo -e "${YELLOW}Restarts API Service${NC}"
    echo -e "api ${BLUE}restart${NC} ${LIGHT_BLUE}<apiName>${NC}"
    echo ""
    echo -e "${YELLOW}Lists all API services${NC}"
    echo -e "api ${BLUE}list${NC}"
    exit 1
fi

command="$1"
apiName="$2"

declare -A apiPaths
apiPaths["wor"]="/home/paarmy/public_html/api.wortool.com/"
apiPaths["pa"]="/home/tonewebdesign/public_html/api.tonewebdesign.com/"
apiPaths["juwanji"]="/home/tonewebdesign/public_html/api.tonewebdesign.com/"

if [ "$command" == "list" ]; then
    echo -e "${YELLOW}List of APIs:${NC}"
    for api in "${!apiPaths[@]}"; do
        echo -e "  ${LIGHT_BLUE}$api${NC}"
    done
    echo ""
    echo -e "${YELLOW}You may restart an API service by using:${NC}"
    echo -e "  api ${BLUE}restart${NC} ${LIGHT_BLUE}<apiName>${NC}"
elif [ "$command" == "restart" ]; then
    if [ -z "$apiName" ] || [ -z "${apiPaths[$apiName]}" ]; then
        echo -e "${GREEN}Usage:${NC} api ${BLUE}restart${NC} ${LIGHT_BLUE}<apiName>${NC}"
        echo -e "  ${YELLOW}Specify a valid ${LIGHT_BLUE}<apiName>${NC} to restart${NC}"
        exit 1
    fi
    cd "${apiPaths[$apiName]}/${apiName}-api/tmp/"
    touch restart.txt
    echo -e "${YELLOW}Restart file created for API:${NC} ${LIGHT_BLUE}$apiName${NC}"
else
    echo -e "${RED}Invalid command:${NC} $command"
    exit 1
fi
