#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
DARK_BLUE='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

if [ "$#" -lt 1 ]; then
    echo -e "${GREEN}Usage:${NC}"
    echo -e "  ${YELLOW}..prod${NC}      bot ${BLUE}prod${NC} ${DARK_BLUE}<stop/start> <botName>${NC} ${RED}<startFile>${NC}"
    echo -e "  ${YELLOW}..dev${NC}       bot ${BLUE}dev start${NC} ${DARK_BLUE}<botName>${NC} ${RED}<startFile>${NC}"
    echo -e "  ${YELLOW}..list${NC}      bot ${BLUE}list${NC}"
    exit 1
fi

environment="$1"
command="$2"
botName="$3"
startUpFile="$4"

# 222Bot override (in a subdirectory and i'm lazy)
botDirectory="/home/bots/$botName/"
if [ "$botName" == "222bot" ]; then
    botDirectory="/home/bots/222Bot/222-discord-bot"
fi

case "$environment" in
    "prod")
        case "$command" in
            "start")
                echo -e "${GREEN}[Starting]${NC}${YELLOW} Discord bot ${NC}${DARK_BLUE}${botName}${NC} ${YELLOW}in production${NC}"
                forever stop "$botName"
                cd "$botDirectory"
                forever start -a --uid "$botName" "$startUpFile"
                ;;
            "stop")
                echo -e "${RED}[Stopping]${NC}${YELLOW} Discord bot ${DARK_BLUE}${botName}${NC}${YELLOW} in production${NC}"
                forever stop "$botName"
                ;;
            *)
                echo -e "${RED}Invalid command:${NC} $command. Use ${DARK_BLUE}<stop/start/list>${NC}"
                exit 1
                ;;
        esac
        ;;

    "dev")
        if [ "$command" = "start" ]; then
            echo -e "${GREEN}[Starting]${NC} Discord bot ${DARK_BLUE}${botName}${NC}${YELLOW} in development${NC}"
            cd "$botDirectory"
            forever stop "$botName"
            node "$startUpFile"
        else
            echo -e "${RED}Invalid command: $command. Use start.${NC}"
            exit 1
        fi
        ;;

    "list")
        if [ "$botName" == "222bot" ]; then
            echo -e "${YELLOW}Listing bots in production for 222bot${NC}"
            cd "$botDirectory"
            forever list
        else
            echo -e "${YELLOW}Listing bots in production${NC}"
            forever list
        fi
        ;;

    *)
        echo -e "${RED}Invalid environment:${NC} $environment. Use ${DARK_BLUE}<prod/dev/list>${NC}"
        exit 1
        ;;
esac
