#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
LIGHT_BLUE='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}System Information:${NC}"

echo -e "\n${YELLOW}Kernel Version:${NC}"
uname -a

echo -e "\n${YELLOW}CPU Information:${NC}"
lscpu

echo -e "\n${YELLOW}Memory Information:${NC}"
free -h

echo -e "\n${YELLOW}Disk Usage:${NC}"
df -h

echo -e "\n${GREEN}Active Users:${NC}"
w
