#!/bin/bash

echo "Listing PM2 instances for user molex:"
pm2 list
echo ""
echo "Listing PM2 instances for user molexcloud:"
sudo -u molexcloud pm2 list
echo ""
echo "Listing PM2 instances for user wortool:"
sudo -u wortool pm2 list
echo ""
echo "Listing PM2 instances for user paarmy:"
sudo -u paarmy pm2 list
echo ""
echo "Listing PM2 instances for user twotwotwo:"
sudo -u twotwotwo pm2 list