#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
LIGHT_BLUE='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

if [ -n "$1" ]; then
    DIRECTORY="$1"
else
    DIRECTORY=$(pwd)
fi

find "$DIRECTORY" -maxdepth 1 -type l -print | while read -r link; do
    target=$(readlink "$link")
    link_name=$(basename "$link")

    formatted="${LIGHT_BLUE}${link_name}${NC}\n${BLUE}   ➥ ${target}${NC}"
    echo -e "$formatted"
done
echo ""
echo -e "${YELLOW}You may ${NC}cd ${LIGHT_BLUE}<symLink>${NC} ${YELLOW}to change directory${NC}"
echo ""
